"""Regenerate FromPandemicCode/HA_Fiscal_calibration.json from the LIVE GE
stage (ruling R-h, 2026-08-10).

The json had no writer since 2026-06 (its old "generated by
HA-Fiscal-HANK-SAM.py" header was false), had drifted against the live GE
constants, and was internally inconsistent (its ss_dstn predated the
per-education chains). This script makes the live engine the single source:
it runs the GE stage with HAFISCAL_HANK_SS_DUMP set, then serializes the
dumped, actually-used steady-state calibration into the json (schema kept
compatible with the old file: same sections and keys, plus per-education
detail and provenance).

Run (any cwd):  python Code/HA-Models/step4/write_calibration_json.py

Side effect: the GE stage also rewrites the multiplier pickle
(Results_HANK/multipliers_across_horizon_w_splurge.obj) at current
defaults — the same artifact `step4/run_ge.py` maintains.
"""
import json
import os
import pickle
import subprocess
import sys
import tempfile
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
HA = os.path.dirname(HERE)
JSON_PATH = os.path.join(HA, "FromPandemicCode", "HA_Fiscal_calibration.json")


def main():
    fd, dump = tempfile.mkstemp(suffix="_ss_dump.obj")
    os.close(fd)
    env = dict(os.environ)
    env["HAFISCAL_HANK_SS_DUMP"] = dump
    try:
        subprocess.run([sys.executable, os.path.join(HERE, "run_ge.py")],
                       env=env, check=True)
        with open(dump, "rb") as f:
            ss = pickle.load(f)
    finally:
        os.unlink(dump)

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                cwd=HA, capture_output=True,
                                text=True).stdout.strip()
    except Exception:
        commit = "unknown"

    out = {
        "_comment": ("Calibration values for the HANK-SAM model, as resolved "
                     "and used by the LIVE GE stage (Code/HA-Models/step4/"
                     "ge.py). Regenerate with: python Code/HA-Models/step4/"
                     "write_calibration_json.py"),
        "_generated_from": (f"step4/write_calibration_json.py at commit "
                            f"{commit} on {date.today().isoformat()} "
                            f"(HAFISCAL_HANK_SS_DUMP of a run_ge.py run at "
                            f"current defaults)"),
    }
    out.update(ss)

    old = {}
    if os.path.exists(JSON_PATH):
        with open(JSON_PATH) as f:
            old = json.load(f)

    with open(JSON_PATH, "w") as f:
        json.dump(out, f, indent=2)
        f.write("\n")

    # Value-diff report against the previous file (leaf keys present in both)
    def leaves(d, pre=""):
        for k, v in d.items():
            if k.startswith("_"):
                continue
            if isinstance(v, dict):
                yield from leaves(v, pre + k + ".")
            elif isinstance(v, (int, float)):
                yield pre + k, float(v)

    old_l, new_l = dict(leaves(old)), dict(leaves(out))
    changed = [(k, old_l[k], new_l[k]) for k in sorted(new_l)
               if k in old_l and abs(new_l[k] - old_l[k])
               > 1e-12 * max(1.0, abs(old_l[k]))]
    print(f"[write-calibration-json] wrote {JSON_PATH}")
    print(f"[write-calibration-json] {len(changed)} changed leaf value(s) "
          f"vs the previous file:")
    for k, o, n in changed:
        rel = (n - o) / o * 100 if o else float("inf")
        print(f"  {k:42s} {o:.6g} -> {n:.6g}  ({rel:+.1f}%)")
    dropped = sorted(set(old_l) - set(new_l))
    if dropped:
        print(f"[write-calibration-json] keys no longer emitted: {dropped}")


if __name__ == "__main__":
    main()
