"""Standalone per-scenario MC runner for welfare-6.

Runs ONE scenario from the welfare-6 pipeline (as a single subprocess)
and pickles the agent-level consumption/income arrays needed by the
welfare-6 formula. Together with `run_welfare6_parallel.py`, this
replaces the serial loop in `run_hybrid_welfare6.py` with subprocess-
level parallelism.

The economy-build and scenario-dispatch code mirror `run_hybrid_welfare6.py`
exactly so that, when every scenario is run once via this script, the
combined results reproduce the serial pipeline bit-for-bit (validated
by `run_welfare6_scenario_vs_serial.py`). Do not edit this file to
diverge from `run_hybrid_welfare6.py`'s setup without also updating
the validation.

Scenarios:
    base                — no-recession base MC
    Check|UI|TaxCut     — no-recession + policy
    recession           — recession, no AD, no policy (for AD=0 denominators)
    recessionUI|recessionCheck|recessionTaxCut — recession + policy, no AD
    recession_AD        — recession with AD convergence, no policy
    recessionUI_AD|recessionCheck_AD|recessionTaxCut_AD — recession + policy, AD

Usage (single-scenario subprocess):
    python welfare6_scenario.py --scenario recessionUI_AD --baseline
    # writes welfare6_scenario_results/recessionUI_AD.pkl
"""

import os

# CRITICAL: limit BLAS thread pools to 1 before any numpy-using library
# is imported. When we fork worker processes for type-parallel solve,
# each child inherits the BLAS thread pool; on macOS with Accelerate
# (VecLib), N forked children × M default threads = oversubscription
# that flattens speedup to ~1.2x even with 3-way parallelism. Setting
# these env vars here (before numpy) gives single-threaded BLAS in the
# parent and all forked children, so N workers use N cores cleanly.
os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")
# NUMBA_NUM_THREADS: HARK interpolation/utilities kernels have their own numba
# pool. Step-5a (AggFiscalMAIN_reduced) has pinned this since its pin block was
# written — its comment claims this file "already pins these", which was FALSE
# for numba until 2026-08-03, when the mac fork certification measured the
# consequence: on macOS numba's darwin `workqueue` layer spun up 18 workers
# whose per-dispatch fork-join overhead made the 21-cohort sequential solve
# ~4x slower than the dell anchor (941s -> >70 min). Linux threading layers
# hide the overhead, which is why dell never showed it. Byte-safety on dell
# verified by the 12-pkl battery gate before this landed (see
# plans/20260803-1600h_machine-probe-portability-critique-and-revision.md §5).
os.environ.setdefault("NUMBA_NUM_THREADS", "1")

import argparse
import multiprocessing
import pickle
import sys
from copy import deepcopy
from time import time

import numpy as np

# Module-level handles for the duration-parallel worker pool.
# The worker reads _POOL_ECO after fork; setting it before Pool() means
# all forked children inherit the solved-economy reference via CoW
# without any pickling of AggEco across process boundaries.
_POOL_ECO = None
_POOL_FULL_OUTPUT = "ForWelfare"

# Module-level handles for the type-parallel solve worker pool.
# _POOL_AGENTS is populated (by the patched AggregateDemandEconomy.solve
# below) in the parent right before fork; children read it after fork.
# _SOLVE_WORKERS is the number of pool workers to use (1 = serial path).
# Default seeded from HAFISCAL_PARALLEL_SOLVE env var if set, else --solve-workers
# CLI arg, else 1.
_POOL_AGENTS = None
_SOLVE_WORKERS = 1
# Honor env var override at import time (so non-CLI entry points like the
# bench harness can set HAFISCAL_PARALLEL_SOLVE=N without touching argv).
_env_workers = os.environ.get('HAFISCAL_PARALLEL_SOLVE', '').strip()
if _env_workers.isdigit():
    _SOLVE_WORKERS = max(1, int(_env_workers))


def _pool_worker(d):
    """Run one recession-duration experiment in a forked child process."""
    return _POOL_ECO.run_experiment(**d, Full_Output=_POOL_FULL_OUTPUT)


def _solve_agent_worker(payload):
    """Solve one agent in a child process. Returns (idx, solution).
    `from_solution` is the warm-start seed computed in the parent.
    pre_solve and post_solve are called in the parent, not here, because
    they mutate agent state that must persist after the pool exits.

    Payload shape: (idx, agent, from_solution). The agent is now passed
    through the payload (pickled) rather than via the _POOL_AGENTS global,
    because the spawn context doesn't inherit parent state.

    Honors HAFISCAL_USE_JAX_2B=1: each worker process uses the JAX-native
    iter loop for its own cohort. Combined with multi-process cohort
    parallelism this gives Nx (cores) * 1.66x (2B) = compound speedup."""
    idx, agent, from_solution = payload
    if os.environ.get('HAFISCAL_USE_JAX_2B', '').lower() in ('1', 'on', 'true'):
        _jax_dir = os.path.abspath(os.path.join(
            os.path.dirname(__file__), '..', 'jax_mc_speedup'))
        if _jax_dir not in sys.path:
            sys.path.insert(0, _jax_dir)
        from jax_solver_iterated_drop_in import solve_to_convergence_consumer_solution
        solution = solve_to_convergence_consumer_solution(
            agent, from_solution=from_solution, max_iters=500, tol=1e-7,
            verbose=False)
    else:
        from HARK.core import solve_agent
        from AggFiscalModel import maybe_accel_solution
        # Universal-acceleration router (plan §C14): welfare6's own pool
        # worker was the un-routed third site — welfare6 monkey-patches
        # AggregateDemandEconomy.solve (:325), so the economy-ladder route
        # never runs here and the agent-level override is bypassed by the
        # direct solve_agent call below.
        solution = maybe_accel_solution(agent, from_solution)
        if solution is None:
            solution = solve_agent(agent, False, from_solution=from_solution)
    return idx, solution

os.environ["MPLBACKEND"] = "Agg"
import matplotlib  # noqa: E402
matplotlib.use("Agg")

HERE = os.path.dirname(os.path.abspath(__file__))
if os.getcwd() != HERE:
    os.chdir(HERE)
sys.path.insert(0, HERE)

_ORIG_ARGV = sys.argv[:]


def _emit_provenance_sidecar(output_dirs, *, label=None, output_roots=None):
    """Best-effort: drop a RUN_<run_id>.prov.json next to this run's outputs.

    Unified run-provenance emitter (Code/HA-Models/provenance.py). Never raises —
    a provenance failure must not abort the simulation."""
    try:
        _ha = os.path.abspath(os.path.join(HERE, ".."))
        if _ha not in sys.path:
            sys.path.insert(0, _ha)
        import provenance as _prov
        _prov.emit(output_dirs, command=" ".join(_ORIG_ARGV), argv=_ORIG_ARGV,
                   label=label, output_roots=output_roots, verbose=True)
    except Exception as _e:  # pragma: no cover - best-effort
        print(f"[provenance] sidecar emit skipped (non-fatal): {_e}")


# Preserve any argv tokens Parameters.py needs (numeric overrides for
# Rfree, CRRA, IncUnemp used by sensitivity parametrizations like CRRA1,
# CRRA3, Rfree_1005, etc.). Strip only our own flags so that
# `Parameters.return_parameters(Parametrization='CRRA1')` can still see
# the relevant numeric args on sys.argv.
_MY_FLAGS_WITH_VALUE = {
    "--scenario", "--parametrization", "--solve-workers",
    "--duration-workers", "--ad-tolerance", "--agent-count-total",
    "--out-dir", "--seed-offset",
}
_MY_FLAGS_NO_VALUE = {"--baseline", "-h", "--help"}
_ALL_MY_FLAGS = _MY_FLAGS_WITH_VALUE | _MY_FLAGS_NO_VALUE
_preserved = []
_i = 1
while _i < len(_ORIG_ARGV):
    _tok = _ORIG_ARGV[_i]
    if "=" in _tok and _tok.split("=", 1)[0] in _ALL_MY_FLAGS:
        _i += 1
        continue
    if _tok in _MY_FLAGS_WITH_VALUE:
        _i += 2
        continue
    if _tok in _MY_FLAGS_NO_VALUE:
        _i += 1
        continue
    _preserved.append(_tok)
    _i += 1
sys.argv = [_ORIG_ARGV[0]] + _preserved

from AggFiscalModel import AggFiscalType, AggregateDemandEconomy  # noqa: E402
from HARK.distributions import DiscreteDistribution  # noqa: E402
from Parameters import return_parameters  # noqa: E402

# Save a reference to the original serial solve so we can (a) fall back
# to it when _SOLVE_WORKERS <= 1 and (b) use the parent-side warm-start
# logic identically in the parallel path.
_ORIG_AGG_SOLVE = AggregateDemandEconomy.solve

# Persistent module-level worker Pool. Created on first call to
# _parallel_agg_solve with _SOLVE_WORKERS > 1 and reused across all
# subsequent eco.solve() calls in the same process. Eliminates the
# 60-120 s/iter spawn overhead seen in the parallel3+spawn experiment
# (workers re-import HARK + re-JIT JAX kernels each time a fresh Pool
# was created). Workers stay warm across AD outer iters and keep their
# JIT cache populated.
_PERSISTENT_POOL = None
_PERSISTENT_POOL_SIZE = 0


def _cleanup_persistent_pool():
    """atexit cleanup for the persistent Pool."""
    global _PERSISTENT_POOL, _PERSISTENT_POOL_SIZE
    if _PERSISTENT_POOL is not None:
        try:
            _PERSISTENT_POOL.terminate()
            _PERSISTENT_POOL.join()
        except Exception:
            pass
        _PERSISTENT_POOL = None
        _PERSISTENT_POOL_SIZE = 0


def _get_persistent_pool(n_workers):
    """Lazily create a spawn-context Pool of n_workers workers. If the pool
    already exists at the right size, reuse it; if size differs, recreate."""
    global _PERSISTENT_POOL, _PERSISTENT_POOL_SIZE
    import atexit
    if _PERSISTENT_POOL is not None and _PERSISTENT_POOL_SIZE == n_workers:
        return _PERSISTENT_POOL
    # Need to (re)create
    if _PERSISTENT_POOL is not None:
        _cleanup_persistent_pool()
    mp_ctx = multiprocessing.get_context("spawn")
    _PERSISTENT_POOL = mp_ctx.Pool(n_workers)
    _PERSISTENT_POOL_SIZE = n_workers
    # Register cleanup the first time we create the pool (atexit dedups by
    # function identity, so re-registering is harmless)
    atexit.register(_cleanup_persistent_pool)
    return _PERSISTENT_POOL


def _sync_mrkv_prev(eco):
    """Record that every agent is now solved against the CURRENT MrkvArray.

    BUG-064. `run_experiment` calls `ThisType.solve_if_changed()`, which re-solves
    whenever `MrkvArray != MrkvArray_prev` (`AggFiscalModel.py:1443`).
    `switch_shock_type` swaps `MrkvArray` (6x6 base -> 132x132 recession) and
    neither `Market.solve()` nor `restore_ADsolution` updates `MrkvArray_prev`, so
    the guard fired on a solve that had ALREADY happened -- re-deriving the same
    policy bit-for-bit (measured move 0.000e+00; panels agree to 4e-16).

    This is the ONE definition of the policy. It is called from exactly three
    places, each being a point where the invariant can be established or broken:

      1. `_parallel_agg_solve` (below) -- the end of every welfare6 economy solve.
         This is the SOURCE: when solve() returns, the invariant is true by
         construction, so that is where it gets recorded, and every caller
         inherits it including ones not yet written.
      2. `run_recession_AD` after `restore_ADsolution` -- REQUIRED, because that
         path installs a stored solution WITHOUT solving, so (1) never runs.
      3. `_prob_weighted_rec` before the fork -- strictly redundant given (1) and
         (2), kept as the last line of defence in front of the pool and pinned by
         `test_duration_no_resolve.py`.

    Placing it per-caller is what failed twice: the 2026-07-29 fix went into the AD
    path only, and the 2026-07-30 fix went into `_prob_weighted_rec`, which
    `run_norec` does not call -- it invokes `run_experiment` directly
    (`welfare6_scenario.py:615`), so three scenarios kept paying the re-solve. At
    HS_Only that was 32.6 s of `UI`'s 61 s wall; at Baseline ~5000 s of 6395 s.
    """
    for agent in eco.agents:
        if hasattr(agent, "MrkvArray"):
            agent.MrkvArray_prev = agent.MrkvArray


def _parallel_agg_solve(self, warm_start=True):
    """Monkey-patched replacement for AggregateDemandEconomy.solve.

    When `_SOLVE_WORKERS <= 1`, defers to the original serial implementation.
    When `_SOLVE_WORKERS > 1`, uses a persistent module-level Pool of
    spawn-context workers (created on first use, reused across calls).
    Workers run 2B (HAFISCAL_USE_JAX_2B=1) or plain HARK solve_agent
    per cohort.

    Either way it finishes by recording the BUG-064 invariant (see
    `_sync_mrkv_prev`): the agents are now solved against the current MrkvArray.
    """
    if _SOLVE_WORKERS <= 1:
        _ret = _ORIG_AGG_SOLVE(self, warm_start=warm_start)
        _sync_mrkv_prev(self)
        return _ret

    # Prepare warm-start solutions in the parent. Also call pre_solve
    # here so the mutations are baked into the agent before it's pickled
    # off to a worker.
    payloads = []
    for i, agent in enumerate(self.agents):
        from_solution = None
        if warm_start and hasattr(agent, 'solution') and len(agent.solution) > 0:
            prev_sol = agent.solution[0]
            current_states = agent.MrkvArray[0].shape[0]
            prev_states = (
                len(prev_sol.vPfunc) if hasattr(prev_sol, 'vPfunc') else 0
            )
            if prev_states == current_states:
                from_solution = prev_sol
        agent.pre_solve()
        # Payload includes the agent itself (pickled to the worker);
        # spawn context doesn't inherit parent globals.
        payloads.append((i, agent, from_solution))

    # Load-balance: sort payloads by descending DiscFac (heuristic — high-β
    # cohorts have larger wealth → wider EGM grids → longer per-cohort
    # solve). With imap_unordered + chunksize=1, workers pick up next-largest
    # task as they finish previous ones, minimizing the longest-cohort tail.
    sorted_idx = sorted(range(len(payloads)),
                        key=lambda k: -float(payloads[k][1].DiscFac))
    payloads_sorted = [payloads[k] for k in sorted_idx]

    # Persistent Pool: reused across eco.solve() calls. First call creates
    # the workers (each ~10-30 s to import HARK + JAX); subsequent calls
    # dispatch directly to warm workers with hot JIT caches.
    pool = _get_persistent_pool(_SOLVE_WORKERS)
    results = list(pool.imap_unordered(
        _solve_agent_worker, payloads_sorted, chunksize=1))

    # Install solutions and run post_solve on the parent's agents.
    # imap_unordered returns in completion order, but each (idx, solution)
    # carries its own cohort index so order doesn't matter for assignment.
    for idx, solution in results:
        self.agents[idx].solution = solution
        self.agents[idx].post_solve()

    _sync_mrkv_prev(self)   # BUG-064 invariant; see _sync_mrkv_prev


# Install the monkey-patch at import time. Effect is process-local;
# AggFiscalModel.py on disk is unchanged.
AggregateDemandEconomy.solve = _parallel_agg_solve

SCENARIOS = (
    "base",
    "Check", "UI", "TaxCut",
    "recession", "recessionUI", "recessionCheck", "recessionTaxCut",
    "recession_AD", "recessionUI_AD",
    "recessionCheck_AD", "recessionTaxCut_AD",
)


def build_and_solve(parametrization, agent_count_total=None, seed_offset=0):
    """Economy build + solve. Mirrors run_hybrid_welfare6.py lines 47-144.

    agent_count_total: if not None, overrides AgentCountTotal from
    Parameters.py. Useful for speed/precision sensitivity sweeps.

    seed_offset: integer added to per-agent-type RNG seeds and to
    IncShkDstn[0].seed to produce an independent multi-seed batch.
    Default 0 reproduces the canonical single-seed run. Pickles
    generated with different seed_offsets share simulation parameters
    but use independent shock realizations; their per-agent panels
    can be concatenated post-hoc to reduce welfare6 SE by 1/√S where
    S is the number of seeds combined."""
    (
        init_dropout, init_highschool, init_college,
        init_ADEconomy, DiscFacDstns, DiscFacCount, AgentCountTotal,
        base_dict, num_max_iterations_solvingAD,
        convergence_tol_solvingAD, UBspell_normal, num_base_MrkvStates,
        data_EducShares, max_recession_duration, num_experiment_periods,
        recession_changes, UI_changes, recession_UI_changes,
        TaxCut_changes, recession_TaxCut_changes,
        Check_changes, recession_Check_changes,
    ) = return_parameters(Parametrization=parametrization, OutputFor="_Main.py")

    if agent_count_total is not None:
        AgentCountTotal = int(agent_count_total)

    [_, Rspell, Rfree_base, _, CRRA] = return_parameters(
        Parametrization=parametrization, OutputFor="_Output_Results.py")
    Rfree = Rfree_base[0]

    init_params = [init_dropout, init_highschool, init_college]

    # HAFISCAL_AGENTCOUNT_{D,H,C} cohort-N override (mirrors the pattern in
    # Simulate.py:289-294). When set, the env var gives the TOTAL N for that
    # education group (across all DiscFacCount β-atoms); per-β-atom AgentCount
    # is then floor(N_cohort × pmv[b]). Each β-atom defaults to uniform pmv = 1/DiscFacCount
    # if pmv is absent (matches HAFiscal default).
    _per_cohort_N_env = {
        0: os.environ.get('HAFISCAL_AGENTCOUNT_D', '').strip(),
        1: os.environ.get('HAFISCAL_AGENTCOUNT_H', '').strip(),
        2: os.environ.get('HAFISCAL_AGENTCOUNT_C', '').strip(),
    }
    _per_cohort_N = {e: int(v) for e, v in _per_cohort_N_env.items() if v}
    if _per_cohort_N:
        print(f'[welfare6 agentcount-override] per-cohort N: {_per_cohort_N}')

    AgentTypes = []
    for e in range(3):
        if data_EducShares[e] <= 0.0:
            continue
        for d in range(DiscFacCount):
            t = AggFiscalType(**init_params[e])
            t.cycles = 0
            t.DiscFac = DiscFacDstns[e].atoms[0][d]
            # seed_offset shifts the per-type seed by a stride of 10000
            # (large enough to avoid collisions with neighbouring offsets'
            # 3*DiscFacCount native indices) so each multi-seed batch
            # uses independent agent-RNG streams.
            t.seed = e * DiscFacCount + d + seed_offset * 10000
            if e in _per_cohort_N:
                # Cohort-N override: split N_cohort across β-atoms by pmv.
                pmv_b = float(DiscFacDstns[e].pmv[d])
                t.AgentCount = int(np.floor(_per_cohort_N[e] * pmv_b))
            else:
                t.AgentCount = int(np.floor(
                    AgentCountTotal * data_EducShares[e] / DiscFacCount
                ))
            AgentTypes.append(t)

    AggEco = AggregateDemandEconomy(**init_ADEconomy)
    AggEco.agents = AgentTypes

    # MC variance-reduction shuffle (mirrors Simulate.py:327-336). When env
    # vars set, attach mc_shuffle / income_shuffle / markov_shuffle attrs to
    # each agent type so HARK 0.17's sim path replaces stochastic draws with
    # deterministic shuffles.
    _mc_shuffle = os.environ.get('HAFISCAL_MC_SHUFFLE', '') == '1'
    _income_shuffle = os.environ.get('HAFISCAL_INCOME_SHUFFLE', '') == '1'
    _markov_shuffle = os.environ.get('HAFISCAL_MARKOV_SHUFFLE', '') == '1'
    if _mc_shuffle or _income_shuffle or _markov_shuffle:
        for _t in AgentTypes:
            _t.mc_shuffle = _mc_shuffle
            _t.income_shuffle = _income_shuffle
            _t.markov_shuffle = _markov_shuffle
        print(f'[welfare6 shuffle] mc_shuffle={_mc_shuffle}  '
              f'income_shuffle={_income_shuffle}  markov_shuffle={_markov_shuffle}')

    # Diagnostic: turn off all mortality (set mortality_off attr on all agents).
    # Used for shuffle-vs-nshuf verification under simplified deterministic-income
    # model (combine with HAFISCAL_PERM_DURING_UNEMP=off).
    if os.environ.get('HAFISCAL_MORTALITY_OFF', '') == '1':
        for _t in AgentTypes:
            _t.mortality_off = True
        print(f'[welfare6 mortality] HAFISCAL_MORTALITY_OFF=1 → mortality disabled '
              f'(all agents have mortality_off=True)')

    # BUG-043 fix: under bug_fix mode, the micro state space has 6 states
    # (e, u1Q, u2Q, u3Q, u4Q, noBen) instead of 4. The u3Q and u4Q states
    # pay IncUnempNoBenefits in non-UI scenarios (= same as noBen, so the
    # added states are welfare-equivalent to noBen in those scenarios).
    # Under recessionUI, u3Q and u4Q pay IncUnemp ONLY when the macro state
    # corresponds to recession (= odd-indexed macro states).
    from EstimParameters import HAFISCAL_UI_STATE_ENCODING, Policy_ExtraBenefitQuarters

    for a in AggEco.agents:
        a.get_economy_data(AggEco)
        IncShkDstn_unemp = DiscreteDistribution(
            np.array([1.0]), [np.array([1.0]), np.array([a.IncUnemp])])
        IncShkDstn_unemp_nobenefits = DiscreteDistribution(
            np.array([1.0]),
            [np.array([1.0]), np.array([a.IncUnempNoBenefits])])
        a.IncShkDstn[0].seed = 763607780 + seed_offset
        a.IncShkDstn[0].reset()
        EmployedIncShkDstn = deepcopy(a.IncShkDstn[0])

        # Per-micro-state IncShkDstn list. Order: [employed, u1Q, u2Q, ..., noBen]
        # Length = num_base_MrkvStates (4 in legacy, 6 in bug_fix).
        if HAFISCAL_UI_STATE_ENCODING == 'bug_fix':
            # 6 entries: e, u1Q, u2Q, u3Q, u4Q, noBen
            # u3Q, u4Q pay no_benefits by default (overridden for recessionUI below)
            a.IncShkDstn = [
                [a.IncShkDstn[0]]
                + [IncShkDstn_unemp] * UBspell_normal
                + [IncShkDstn_unemp_nobenefits] * Policy_ExtraBenefitQuarters
                + [IncShkDstn_unemp_nobenefits]
            ]
        else:
            # Legacy 4 entries: e, u1Q, u2Q, noBen
            a.IncShkDstn = [
                [a.IncShkDstn[0]]
                + [IncShkDstn_unemp] * UBspell_normal
                + [IncShkDstn_unemp_nobenefits]
            ]
        a.IncShkDstn_base = a.IncShkDstn
        IncShkDstn_recession = [
            a.IncShkDstn[0] * (2 * (num_experiment_periods + 1))
        ]
        a.IncShkDstn_recession = IncShkDstn_recession

        # BUG-043: for recessionUI under bug_fix mode, override u3Q/u4Q income
        # at recession macro states to be IncUnemp (= extension active).
        # For non-recession macro states, leave as IncUnempNoBenefits (= extension
        # expires when recession ends). For legacy mode, recessionUI uses the
        # same income vector as recession (the policy difference is encoded via
        # transition_ub=False in MrkvArray_recessionUI; see BUG-043 dossier).
        if HAFISCAL_UI_STATE_ENCODING == 'bug_fix':
            IncShkDstn_recessionUI = deepcopy(IncShkDstn_recession)
            n_macro = 2 * (num_experiment_periods + 1)
            # u3Q, u4Q micro indices = UBspell_normal + 1 .. UBspell_normal + Policy_ExtraBenefitQuarters
            extension_micro_indices = list(range(
                UBspell_normal + 1,
                UBspell_normal + 1 + Policy_ExtraBenefitQuarters,
            ))
            for macro_idx in range(n_macro):
                # Even macro indices = "normal at time t", odd = "recession at time t".
                # Extension only active during recession macro states.
                if macro_idx % 2 == 1:  # recession
                    for micro_idx in extension_micro_indices:
                        combined = macro_idx * num_base_MrkvStates + micro_idx
                        IncShkDstn_recessionUI[0][combined] = IncShkDstn_unemp
            a.IncShkDstn_recessionUI = IncShkDstn_recessionUI
        else:
            a.IncShkDstn_recessionUI = IncShkDstn_recession

        EmployedIncShkDstn_tc = deepcopy(EmployedIncShkDstn)
        # BUG-023 fix (2026-05-13): rescale all TranShk atoms (atoms[1] is
        # TranShk per HARK convention), not the second PermShk atom. The
        # previous "atoms[0][1] *= TaxCutIncFactor" mutated PermShk[1] by
        # ×1.02, making the tax cut almost invisible in TM-a. MC was
        # unaffected because Simulate.py:744-765 delivers TaxCut via
        # tran_shock_fixed_hist × tax_cut_multiplier, bypassing this
        # IncShkDstn override. See BUGS_private/HAFiscal_BUG-023_*.md
        # "Update 2026-05-13" for full diagnosis + verification plan.
        EmployedIncShkDstn_tc.atoms = (
            np.asarray(EmployedIncShkDstn_tc.atoms[0], dtype=np.float64),
            np.asarray(EmployedIncShkDstn_tc.atoms[1], dtype=np.float64) * a.TaxCutIncFactor,
        )
        # TaxCutStatesIncShkDstn matches the per-micro-state structure of a.IncShkDstn[0]
        if HAFISCAL_UI_STATE_ENCODING == 'bug_fix':
            TaxCutStatesIncShkDstn = (
                [EmployedIncShkDstn_tc]
                + [IncShkDstn_unemp] * UBspell_normal
                + [IncShkDstn_unemp_nobenefits] * Policy_ExtraBenefitQuarters
                + [IncShkDstn_unemp_nobenefits]
            )
        else:
            TaxCutStatesIncShkDstn = (
                [EmployedIncShkDstn_tc]
                + [IncShkDstn_unemp] * UBspell_normal
                + [IncShkDstn_unemp_nobenefits]
            )
        IncShkDstn_recessionTaxCut = deepcopy(IncShkDstn_recession)
        for i in range(
            2 * num_base_MrkvStates,
            2 * (num_experiment_periods + 1) * num_base_MrkvStates,
        ):
            IncShkDstn_recessionTaxCut[0][i] = TaxCutStatesIncShkDstn[
                np.mod(i, num_base_MrkvStates)
            ]
        a.IncShkDstn_recessionTaxCut = IncShkDstn_recessionTaxCut
        a.IncShkDstn_recessionCheck = deepcopy(IncShkDstn_recession)

    # Opt-in JAX solver: replaces agent.solve_one_period with the JAX implementation
    # (P1-P6 validated at HS_Only recession to <1e-3 vs HARK). Activated via
    # HAFISCAL_USE_JAX_SOLVER=1. Currently the JAX path is correctness-validated but
    # ~4.6× slower than HARK at recession scale due to Python dispatch overhead in
    # HARK's iter loop — use only for kernel-correctness regression testing today.
    # See project_jax_solver_port_p1_p6_status_2026_05_19 for perf characterization.
    if os.environ.get('HAFISCAL_USE_JAX_SOLVER', '0') == '1':
        try:
            from jax_solver_drop_in import install_jax_solver
            for _ag in AggEco.agents:
                install_jax_solver(_ag)
            print(f"[welfare6] HAFISCAL_USE_JAX_SOLVER=1 → installed JAX solver "
                  f"on {len(AggEco.agents)} agents", flush=True)
        except ImportError as _e:
            print(f"[welfare6] HAFISCAL_USE_JAX_SOLVER set but JAX import failed: {_e}",
                  flush=True)

    # Cache-aware initial solve (HAFISCAL_USE_SOLUTION_CACHE=1).
    # Falls through to plain AggEco.solve() if cache off.
    _scache_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..")
    if _scache_path not in sys.path:
        sys.path.insert(0, _scache_path)
    from solution_cache import cached_eco_solve
    cached_eco_solve(
        {"AggEco": AggEco}, shock_type="base",
        mc_method="hark_solve_only", seeds=(0,), use_shuffle=False,
        verbose=True,
    )

    # Burn-in + switch to counterfactual mode
    AggEco.reset()
    for a in AggEco.agents:
        a.initialize_sim()
        a.AggDemandFac = 1.0
        a.RfreeNow = 1.0
        a.CaggNow = 1.0
    AggEco.make_history()
    # [2026-06-08] DEFAULT ON (BUG-052 fix): route the MC init through the SAME TM-ergodic
    # warm-start the multiplier pipeline (Simulate.py) uses, instead of the cold-start. The
    # welfare experiment MUST start at the ergodic wealth the beta-calibration targets (the
    # estimation burns in T_sim=T_age*2 and settles to E[aNrm]~=0.31); cold-starting at a~=0
    # is a calibration inconsistency (BUG-052). Injected AFTER make_history / BEFORE save_state
    # so run_experiment's use_prestate (AggFiscalModel:541-542) restores the ergodic prestate.
    # HAFISCAL_WELFARE6_TM_INIT=0 toggles OFF (cold-start) -- for isolation/paper-trail only,
    # NOT a QE-reproduction goal. See BUGS_private/HAFiscal_BUG-052_welfare6_cold_start_vs_ergodic_calibration.md
    if os.environ.get('HAFISCAL_WELFARE6_TM_INIT', '1') != '0':
        from tm_methods import (compute_baseline_tm_data as _cbtd,
                                 initialize_mc_from_tm_ergodic as _imc)
        for a in AggEco.agents:
            a.tm_a_indexed = True
        # P-ergodic (neutral_measure=False) for the ACTUAL-agent MC init — matches
        # Simulate.py's tm_neutral_measure default (False). The Q/Harmenberg ergodic is
        # for TM aggregation, NOT for seeding real agents.
        # NOTE: HAFISCAL_WELFARE6_TM_INIT_MEASURE is DEPRECATED (docs/ENV_FLAGS.md):
        # its only non-default value 'Q' has no valid production use for agent seeding
        # (red herring in the check_rec MC-vs-TM probe; P/Q identical). Default 'P' stands.
        _bd = _cbtd(AggEco, dist_aGrid_count=int(os.environ.get('HAFISCAL_TM_MCOUNT', '200')),
                    neutral_measure=(os.environ.get('HAFISCAL_WELFARE6_TM_INIT_MEASURE', 'P') == 'Q'))
        _imc(AggEco.agents, _bd,
             mc_warmup=int(os.environ.get('HAFISCAL_WELFARE6_MC_WARMUP', '24')))
    AggEco.save_state()
    AggEco.switch_to_counterfactual_mode("base")
    act_T = AggEco.act_T
    for a in AggEco.agents:
        a.T_sim = act_T
        a.EconomyMrkvNow_hist = [0] * act_T
    AggEco.make_idiosyncratic_shock_histories()

    # Whole-cell reseed support: run_recession_AD derives the JAX kernel seeds
    # from this, so a --seed-offset battery moves EVERY RNG input of an AD cell
    # (agent sims, warm-start draws, kernel streams, newborn pool), not just the
    # HARK half. Without it the 4 *_AD cells reuse identical JAX realizations at
    # every offset and a multi-seed SE on the AD welfare row is understated.
    AggEco._welfare6_seed_offset = int(seed_offset)

    return dict(
        AggEco=AggEco,
        base_dict=base_dict,
        recession_changes=recession_changes,
        UI_changes=UI_changes,
        recession_UI_changes=recession_UI_changes,
        TaxCut_changes=TaxCut_changes,
        recession_TaxCut_changes=recession_TaxCut_changes,
        Check_changes=Check_changes,
        recession_Check_changes=recession_Check_changes,
        num_experiment_periods=num_experiment_periods,
        max_recession_duration=max_recession_duration,
        num_max_iterations_solvingAD=num_max_iterations_solvingAD,
        convergence_tol_solvingAD=convergence_tol_solvingAD,
        act_T=act_T,
        Rspell=Rspell,
        Rfree=Rfree,
        CRRA=CRRA,
        parametrization=parametrization,  # for downstream JAX replay verification
    )


def _add_bs_fields(r):
    """Non-recession scenarios are a single realization, so the
    bootstrap-source panel is identical to the primary panel."""
    r["cLvl_all_splurge_bs"] = r["cLvl_all_splurge"]
    r["pLvl_all_bs"]         = r["pLvl_all"]
    r["Mrkv_hist_bs"]        = r["Mrkv_hist"]
    if "aNrm_all" in r:
        r["aNrm_all_bs"]     = r["aNrm_all"]
    if "TranShk_all" in r:
        r["TranShk_all_bs"]  = r["TranShk_all"]
    if "PermShk_all" in r:
        r["PermShk_all_bs"]  = r["PermShk_all"]
    if "who_dies_all" in r:
        r["who_dies_all_bs"] = r["who_dies_all"]
    return r


def run_base(ctx):
    AggEco = ctx["AggEco"]
    base_dict_agg = deepcopy(ctx["base_dict"])
    base_mc = AggEco.run_experiment(**base_dict_agg, Full_Output="ForWelfare")
    AggEco.store_baseline(base_mc["AggCons"])
    return _add_bs_fields(base_mc)


def _ensure_base_solved(eco):
    """R3 companion (2026-08-02): recreate the counterfactual-base solution
    that the base run used to (re)create as a side effect.

    build_and_solve's switch_to_counterfactual_mode DELETES every agent's
    .solution by design (AggFiscalModel.py:1259 — the build solve is the
    "small" pre-recession one, used only for the initial distribution), and
    the FIRST counterfactual-base solve historically happened invisibly
    inside run_base's run_experiment (update_mrkv_array + solve_if_changed).
    store_baseline's snapshot (store_ADsolution) needs that solution, so a
    child that skips the base SIM must still establish the base SOLVE.
    This mirrors run_experiment's pre-loop exactly — per-agent
    update_mrkv_array("base") then a solve — with the solve routed through
    the LOSSLESS policy_full cache (the knot-extraction kind measured
    7.2e-3-lossy: it cannot carry the PF-decay tails; see cache.py's
    policy_full block): the first run solves fresh and publishes, later
    runs (and all battery children) skip solve AND sim exactly. The
    trailing _sync_mrkv_prev is the BUG-064 invariant on the HIT path."""
    for t in eco.agents:
        t.update_mrkv_array("base")
    try:
        from solution_cache import (load_policy_solution_cache,
                                    save_policy_solution_cache)
    except Exception:
        load_policy_solution_cache = save_policy_solution_cache = None
    if (load_policy_solution_cache is not None
            and load_policy_solution_cache(eco, "base")):
        _sync_mrkv_prev(eco)
        return
    eco.solve()
    _sync_mrkv_prev(eco)
    if save_policy_solution_cache is not None:
        save_policy_solution_cache(eco, "base")


def _cached_policy_switch_solve(eco, shock_type):
    """R4b (2026-08-02): the runners' ``switch_shock_type + solve``, routed
    through the solve cache. The policy solve is keyed by shock_type + the
    solved config only (the per-cell ``changes`` are run_experiment kwargs,
    applied AFTER the solve), so the 8 non-AD children share 4 deterministic
    solves — the same ``hark_solve_only`` entries the recession-init pair
    (BUG-052 lever #1) and build_and_solve's base solve already use. HIT
    loads the solved state in place of the ~25-min contended sequential-
    equivalent policy solve (~85% of a non-AD child's wall, R4 profile);
    MISS solves via the (BUG-064-synced, pooled) eco.solve() and publishes.
    Gated by HAFISCAL_USE_SOLUTION_CACHE exactly like every solve-cache
    consumer — cache off reproduces the plain switch+solve path verbatim.
    Uses the LOSSLESS policy_full kind (wholesale-pickled solutions): the
    knot-extraction kind measured 7.2e-3-lossy on installed-without-resolve
    use (PF-decay tails unrepresentable; see cache.py's policy_full block).
    The trailing _sync_mrkv_prev is the BUG-064 invariant on the HIT path
    (case 2 of its taxonomy: a stored solution installed WITHOUT solving),
    a no-op after a MISS-path solve."""
    eco.switch_shock_type(shock_type)
    try:
        from solution_cache import (load_policy_solution_cache,
                                    save_policy_solution_cache)
    except Exception:
        load_policy_solution_cache = save_policy_solution_cache = None
    if (load_policy_solution_cache is not None
            and load_policy_solution_cache(eco, shock_type)):
        _sync_mrkv_prev(eco)
        return
    eco.solve()
    _sync_mrkv_prev(eco)
    if save_policy_solution_cache is not None:
        save_policy_solution_cache(eco, shock_type)


def run_norec(ctx, shock_type, changes):
    AggEco = ctx["AggEco"]
    base_dict_agg = deepcopy(ctx["base_dict"])
    norec_path = (
        list(np.arange(1, ctx["num_experiment_periods"] + 1) * 2) + [0] * 20
    )
    eco = deepcopy(AggEco)
    _cached_policy_switch_solve(eco, shock_type)
    d = base_dict_agg.copy()
    d.update(changes)
    d["EconomyMrkv_init"] = norec_path
    return _add_bs_fields(eco.run_experiment(**d, Full_Output="ForWelfare"))


def _prob_weighted_rec(ctx, eco, changes, duration_workers=1):
    """Run the max_recession_duration MC experiments and average by
    recession-persistence probability. If duration_workers > 1, the
    per-duration loop runs in parallel in forked subprocesses that
    inherit `eco` via copy-on-write (no pickling). Results are
    deterministic and identical to serial execution (validated by
    validate_duration_pool.py).

    PRECONDITION: the caller has just solved `eco` against its current MrkvArray
    (run_recession does eco.solve(); run_recession_AD finishes its AD loop and
    restores the converged solution). BUG-064's sync below relies on it."""
    # BUG-064 -- do not let every forked duration child re-solve the whole economy.
    #
    # run_experiment calls ThisType.solve_if_changed(), which re-solves whenever
    # MrkvArray != MrkvArray_prev. switch_shock_type swaps MrkvArray (6x6 base ->
    # 132x132 recession) and Market.solve() never updates MrkvArray_prev, so on the
    # non-AD path the guard fired on the FIRST task of every fork child: 21 agents,
    # serially, per child. MEASURED 2026-07-30, Baseline recessionCheck, solo box,
    # dw=2: duration loop 3320.6 s -> 208.0 s (16.0x), which is exactly its AD twin's
    # 208.0-238.7 s. Pricing it directly (performing the re-solve in the parent) cost
    # 3329.1 s against an excess of 3112.6 s -- the same quantity.
    #
    # It is NOT the "one extra solve after convergence" sniff test: the discarded
    # re-solve reproduces the policy EXACTLY -- measured move 0.000e+00 at both
    # HS_Only and Baseline, with all result panels agreeing to 4.0e-16 (mean 3e-22),
    # i.e. floating-point summation order. eco.solve() had already solved the agents
    # against this MrkvArray; only the bookkeeping attribute lagged.
    #
    # Synced HERE, not in the callers, so every caller inherits it -- run_recession_AD
    # does the same thing at its own line (kept, now redundant, as documentation of
    # the 2026-07-29 half of this fix, which was applied to the AD path alone).
    # Must run in the PARENT, before the fork, so children inherit the synced state.
    # HAFISCAL_DURATION_RESOLVE=1 restores the old behaviour for A/B work only.
    if os.environ.get("HAFISCAL_DURATION_RESOLVE", "").lower() not in ("1", "on", "true"):
        _sync_mrkv_prev(eco)

    base_dict_agg = deepcopy(ctx["base_dict"])
    Rspell = ctx["Rspell"]
    num_experiment_periods = ctx["num_experiment_periods"]
    max_recession_duration = ctx["max_recession_duration"]
    R_persist = 1.0 - 1.0 / Rspell
    recession_prob = np.array([
        R_persist ** t * (1 - R_persist)
        for t in range(max_recession_duration)
    ])
    recession_prob[-1] = 1.0 - np.sum(recession_prob[:-1])

    # Build per-duration dicts.
    tasks = []
    for dur in range(max_recession_duration):
        d = base_dict_agg.copy()
        d.update(changes)
        rec_path = (
            list(np.arange(1, num_experiment_periods + 1) * 2) + [0] * 20
        )
        rec_path[0 : dur + 1] = (
            np.array(rec_path[0 : dur + 1]) + 1
        ).tolist()
        d["EconomyMrkv_init"] = rec_path
        tasks.append(d)

    # Forking a JAX-loaded process. CPython multiprocessing forks, and JAX warns
    # about it itself ("os.fork() is incompatible with multithreaded code, and JAX
    # is multithreaded, so this will likely lead to a deadlock"): a lock held by a
    # background thread at fork time stays locked forever in the child.
    #
    # BOTH NUMBERS THIS GUARD WAS BUILT ON ARE NOW EXPLAINED BY OTHER CAUSES
    # (2026-07-30), so `auto` re-measures rather than assumes:
    #   * the "15.7x penalty" (JAX arm 3441.5 s vs HARK arm 219.0 s at dw=2,
    #     2026-07-28) was the wasted post-AD re-solve, per the analysis at
    #     run_recession_AD below: HARK's AD loop refreshes MrkvArray_prev through
    #     its own solve() calls and the JAX loop did not, so only the JAX arm paid
    #     it. That is the same defect as BUG-064, on the AD path.
    #   * "the pool does not scale anyway (178.9 s @dw=1 vs 182.6 @dw=2)"
    #     generalised a Reduced-scale NON-AD measurement, which was dominated by
    #     that same per-child re-solve. Re-measured at Baseline on the fixed code
    #     the pool gives 1.70x @dw=2, 3.36x @4, 6.07x @8.
    # So the premise was gone and the guard cost a real ~6x per AD scenario -- but
    # the deadlock hazard is a genuine property of fork(), not an artifact, and it
    # does not announce itself in a wall time, so it was MEASURED rather than
    # reasoned away. R2 probe, Baseline recessionCheck, post-AD economy, JAX
    # imported AND compiled (102 live XLA threads, matching a real AD scenario):
    #
    #   arm      dw=1     dw=8      AggCons
    #   no-jax  361.7s   56.4s    67c2c924f7
    #   jax x3  361.8s   59.1s    67c2c924f7   (54.5 / 62.1 / 60.7)
    #
    # Three repeats at dw=8 because a fork/thread deadlock is a RACE and one clean
    # pass proves little: no hang, 6.12x scaling, and a single AggCons hash across
    # all eight runs. JAX-in-process costs 1.048x at dw=8 -- noise. The duration
    # children never touch JAX (pure HARK/numpy through run_experiment), which is
    # why the classic fork-into-threads hazard does not bite here.
    #
    # Default is therefore 'auto' = keep the pool. HAFISCAL_DURATION_FORK=off
    # restores the forced dw=1 for anyone who hits a hang on other hardware; if
    # that ever happens the right fix is a spawn/forkserver duration pool, not a
    # return to serial.
    _fork_mode = os.environ.get("HAFISCAL_DURATION_FORK", "auto").strip().lower()
    if duration_workers > 1 and 'jax' in sys.modules and _fork_mode == "off":
        print(f"  [_prob_weighted_rec] HAFISCAL_DURATION_FORK=off: forcing "
              f"duration_workers {duration_workers} -> 1 under JAX. Measured cost "
              f"~6.1x on this loop; the default ('auto') keeps the pool.",
              flush=True)
        duration_workers = 1

    t_loop = time()
    if duration_workers <= 1:
        all_results = [eco.run_experiment(**d, Full_Output="ForWelfare")
                       for d in tasks]
    else:
        # Set the module-level eco BEFORE creating the Pool so that
        # forked children inherit the solved-economy reference.
        global _POOL_ECO
        _POOL_ECO = eco
        fork_ctx = multiprocessing.get_context("fork")
        with fork_ctx.Pool(duration_workers) as pool:
            all_results = pool.map(_pool_worker, tasks)
        _POOL_ECO = None
    print(f"  [_prob_weighted_rec] duration loop (n={max_recession_duration}, "
          f"workers={duration_workers}) took {time() - t_loop:.1f}s",
          flush=True)

    avg = {}
    for key in ("cLvl_all_splurge", "AggIncome", "AggCons"):
        avg[key] = np.sum(
            np.array([
                all_results[t][key] * recession_prob[t]
                for t in range(max_recession_duration)
            ]),
            axis=0,
        )
    # Bootstrap-source panel: modal duration (dur=0 is always the mode
    # under the geometric distribution used here). Consumers of the
    # pickle use *_bs fields to recompute MC and MC-L2 welfare on a
    # single duration realization for bootstrap SE estimation.
    avg["cLvl_all_splurge_bs"] = np.asarray(all_results[0]["cLvl_all_splurge"])
    avg["pLvl_all_bs"]         = np.asarray(all_results[0]["pLvl_all"])
    avg["Mrkv_hist_bs"]        = np.asarray(all_results[0]["Mrkv_hist"])
    if "aNrm_all" in all_results[0]:
        avg["aNrm_all_bs"]     = np.asarray(all_results[0]["aNrm_all"])
    # BUG-046 fix (2026-05-16): preserve per-duration cLvl_all_splurge so
    # welfare aggregation can apply u(c) PER DURATION and weight by
    # rec_probs (instead of u(weighted-avg c), which is Jensen-biased by
    # ~−23% for `*_rec` cells with rho=2).
    avg["per_dur_cLvl_all_splurge"] = np.array(
        [all_results[t]["cLvl_all_splurge"] for t in range(max_recession_duration)],
        dtype=np.float64,
    )
    avg["rec_probs"] = recession_prob
    return avg


def run_recession(ctx, shock_type, changes, duration_workers=1):
    AggEco = ctx["AggEco"]
    eco = deepcopy(AggEco)
    _cached_policy_switch_solve(eco, shock_type)
    # Lever #1 (opt-in: HAFISCAL_AD_INIT_CACHE): this no-AD recession solve is
    # bit-identical to the JAX-AD init's ref-sim solve for the same shock_type.
    # Populate the shared recession-init cache so the AD scenario can SKIP its
    # ~945s cold solve. Best-effort + gated -> no effect on the default path.
    try:
        from solution_cache import save_recession_init_cache
        save_recession_init_cache(eco, shock_type)
    except Exception:
        pass
    return _prob_weighted_rec(ctx, eco, changes,
                              duration_workers=duration_workers)


def run_recession_AD(ctx, shock_type, changes, duration_workers=1,
                     ad_tolerance=None):
    AggEco = ctx["AggEco"]
    eco = deepcopy(AggEco)
    eco.switch_shock_type(shock_type)
    num_iter = ctx["num_max_iterations_solvingAD"]
    cutoff = (float(ad_tolerance)
              if ad_tolerance is not None
              else ctx["convergence_tol_solvingAD"])
    t_ad = time()
    use_jax = os.environ.get('HAFISCAL_USE_JAX_MC', '').lower() in ('1', 'on', 'true')
    # Belief-consistent routing (owner ruling 2026-07-27, BUG-054 integration
    # night): the JAX-MC AD kernel requires a finite T_age, so under the
    # uncapped default world it would simulate a DIFFERENT world than the TM
    # engines — in-principle inconsistent MC-vs-TM results. Route uncapped AD
    # through HARK-AD (no-cap exact) at this single choke point so every
    # caller (run_welfare6_parallel's USE_JAX_MC=1 child default included)
    # inherits it. Capped runs (explicit HAFISCAL_T_AGE) keep the JAX path.
    if use_jax and getattr(eco.agents[0], 'T_age', None) is None:
        if os.environ.get('HAFISCAL_USE_JAX_MC_UNCAPPED', '').lower() in ('1', 'on', 'true'):
            print("[welfare6] UNCAPPED JAX EVAL MODE "
                  "(HAFISCAL_USE_JAX_MC_UNCAPPED=1): keeping the JAX-MC path "
                  "via the effective-age-chain port (survivorship-1e-9 "
                  "truncation). Production default remains HARK-AD.")
        else:
            print("[welfare6] HAFISCAL_USE_JAX_MC requested but T_age=None "
                  "(belief-consistent uncapped world): JAX-MC kernel requires a "
                  "finite age cap -> routing AD via HARK-AD (TM-exact, no-cap). "
                  "Set a finite HAFISCAL_T_AGE to use the JAX kernel, or "
                  "HAFISCAL_USE_JAX_MC_UNCAPPED=1 for the EVAL port.")
            use_jax = False
    # JAX path supports all four recession scenarios (validated 2026-05-19; see
    # CLAUDE.md §JAX MC kernel and plans/20260518_step8_recession_scenarios_design.md).
    # 'recession'/'recessionUI' work via agent.IncShkDstn_recessionUI (BUG-043
    # u3Q/u4Q state-conditional overrides baked in); 'recessionCheck'/
    # 'recessionTaxCut' have their policy income paths wired through the AD loop
    # since the 2026-05-18/19 step-8 extension.
    JAX_AD_SUPPORTED_SCENARIOS = {"recession", "recessionUI", "recessionCheck", "recessionTaxCut"}

    # ------------------------------------------------------------------
    # Plan-1 Leg B (consume, default OFF): WARM-START the AD solve from a
    # Step-5a-published belief. This is a STRICT NO-OP unless
    # HAFISCAL_AD_BELIEF_SEED is set — when unset, nothing below touches `eco`,
    # so the downstream solve is byte-identical to today.
    #
    # When set: load the sidecar, compute this run's fingerprint, SOFT-gate on a
    # calibration/regime match (a mismatch only forgoes the speedup — never a
    # correctness hazard, because the seed is ONLY an initial guess), and on a
    # match seed eco.CFunc + each agent.CFunc AND set eco._ad_warm_start=True. We then
    # fall through to the UNCHANGED cached_solve_ad_recession[_hark] call below: its loop
    # runs to its own convergence_cutoff. NO verify, NO skip, NO assert-and-accept.
    #
    # CORRECTNESS BAR — NUMERICAL EQUIVALENCE, not byte-identity. eco._ad_warm_start makes
    # solve_ad_recession skip its flat reset and re-apply the seed after self.update()
    # (AggFiscalModel.py), so the loop genuinely starts warm (MEASURED HS_Only
    # recessionCheck_AD: 4 -> 1 iterations). But a warm and a flat trajectory cross the
    # convergence_cutoff step-threshold at different points, so the converged result is
    # NUMERICALLY EQUIVALENT (welfare reldiff ~9.8e-8, cLvl panel ~2.5e-5) but NOT the
    # same bytes. So this seed is for FRESH / candidate runs; for BYTE-identical fast
    # reproduction of frozen tables use the AD cache (HAFISCAL_USE_SOLUTION_CACHE, Leg A).
    # Default OFF. See plans/20260622_welfare6-reuse-presolved-AD-equilibria.md (Leg B).
    _seed_requested = os.environ.get('HAFISCAL_AD_BELIEF_SEED', '').lower() in ('1', 'on', 'true')
    if _seed_requested:
        _scache_path0 = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "..")
        if _scache_path0 not in sys.path:
            sys.path.insert(0, _scache_path0)
        # --byte-identical (VERIFY level 'byte'): the belief seed is NUMERICAL equivalence, not
        # byte-identity (the warm-start changes the AD convergence PATH → the bytes can differ
        # from a flat start). Force a flat (fresh) start so --byte-identical stays byte-exact.
        try:
            from solution_cache.cache import byte_exact_forces_fresh_solve as _bxf
            if _bxf():
                print("  [ad_belief] SEED skipped under --byte-identical (needs a flat, "
                      "byte-exact start, not a numerically-equivalent warm-start).", flush=True)
                _seed_requested = False
        except Exception:
            pass
    if _seed_requested:
        try:
            from solution_cache import ad_belief as _ad_belief
            from solution_cache.keys import (
                gather_solve_inputs as _gsi, hash_solve_inputs as _hsi)
            _param = ctx.get('parametrization', None)
            _loaded = _ad_belief.load_ad_belief(shock_type, _param)
            if _loaded is None:
                from solution_cache import record_reuse_event as _rre_s0
                _rre_s0("ad_belief_seed", "no_sidecar", "none",
                        shock_type=shock_type)
                print(f"  [ad_belief] SEED: no sidecar for "
                      f"({_param}, {shock_type}); flat start.", flush=True)
            else:
                _belief, _stored_fp, _belief_engine = _loaded
                # mc_method this run actually solves with — matches the tag the
                # cached_solve_ad_recession[_hark] call below keys on.
                _this_mc = ("jax_mc_2d_vmap"
                            if (use_jax and shock_type in JAX_AD_SUPPORTED_SCENARIOS)
                            else "hark_mc")
                # Same-engine fingerprint (ideal match)...
                _fp_same = _hsi(_gsi(eco, shock_type=shock_type, mc_method=_this_mc))
                # ...and the cross-engine TM convention (mc_method=None at publish),
                # which is an ALLOWED warm-start (the seed is only a guess), so a TM
                # belief can still seed an MC run when the CALIBRATION matches.
                _fp_tm = _hsi(_gsi(eco, shock_type=shock_type, mc_method=None))
                _match = (_stored_fp == _fp_same) or (_stored_fp == _fp_tm)
                _cross = _match and (_stored_fp != _fp_same)
                if not _match:
                    from solution_cache import record_reuse_event as _rre_sm
                    _rre_sm("ad_belief_seed", "fingerprint_mismatch", "none",
                            shock_type=shock_type,
                            source_engine=_belief_engine)
                    print(f"  [ad_belief] SEED: fingerprint mismatch for "
                          f"({_param}, {shock_type}) "
                          f"(stored engine={_belief_engine}); ignoring sidecar, "
                          f"flat start.", flush=True)
                    # Abundant degradation diagnostics: log WHICH solve-inputs differ so a
                    # rejected warm-start is debuggable without re-instrumenting by hand.
                    try:
                        print(_ad_belief.describe_fingerprint_mismatch(
                            eco, shock_type, _param, _this_mc), flush=True)
                    except Exception:
                        pass
                else:
                    dim = len(eco.CFunc)
                    if len(_belief) != dim:
                        print(f"  [ad_belief] SEED: state-count mismatch "
                              f"(belief N={len(_belief)} vs eco N={dim}); "
                              f"ignoring sidecar, flat start.", flush=True)
                    else:
                        eco.CFunc = _belief
                        for _ag in eco.agents:
                            _ag.CFunc = eco.CFunc
                        # Make the seed SURVIVE solve_ad_recession's top-of-loop flat
                        # reset (AggFiscalModel.py) — without this the warm start is
                        # inert (the belief is overwritten before the loop). The loop
                        # still runs to its own convergence_cutoff unchanged.
                        eco._ad_warm_start = True
                        from solution_cache import record_reuse_event as _rre_sc
                        _rre_sc("ad_belief_seed", "consumed", "tolerance",
                                shock_type=shock_type,
                                source_engine=_belief_engine,
                                cross_engine=bool(_cross))
                        print(f"  [ad_belief] SEED: warm-started "
                              f"({_param}, {shock_type}) from engine="
                              f"{_belief_engine} belief"
                              f"{' (CROSS-ENGINE)' if _cross else ''}. "
                              f"Loop runs to its own cutoff unchanged; "
                              f"seeded-vs-flat iteration count logged via the "
                              f"AD profiler (_ad_last_iters).", flush=True)
        except Exception as _e:
            # Warm start is optional; any failure must not change the result.
            print(f"  [ad_belief] SEED: skipped ({_e}); flat start.", flush=True)
    # ------------------------------------------------------------------

    if use_jax and shock_type in JAX_AD_SUPPORTED_SCENARIOS:
        if not hasattr(eco, 'base_AggCons'):
            raise RuntimeError("HAFISCAL_USE_JAX_MC requires base_AggCons; "
                               "ensure run_base() ran first.")
        # Cache-aware path: HAFISCAL_USE_SOLUTION_CACHE=1 → cached_solve_ad_recession
        # transparently skips the full AD loop on a cache hit.
        # Falls through to the direct call when cache is off.
        _scache_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "..")
        if _scache_path not in sys.path:
            sys.path.insert(0, _scache_path)
        from solution_cache import cached_solve_ad_recession
        # Kernel seeds move with the build's seed_offset (stride 10, matching the
        # jax_mc seed-variance probes; offset 0 reproduces (0,1,2,3) exactly).
        # The tuple is hashed into the AD cache key, so offsets cannot cross-hit.
        _k = int(getattr(eco, "_welfare6_seed_offset", 0) or 0)
        # Ensemble-size knob (G2b, draw-structure plan): the kernel averages
        # this many seed-streams per AD iteration (default 4, the historical
        # ensemble). HARK-AD iterates on ONE realization, so if the averaging
        # shifts the fixed point (Jensen through the nonlinear AD map), a
        # single-stream kernel should land HARK-like. Keyed for free via the
        # seeds tuple, which is hashed into the AD cache key.
        _n_seeds = int(os.environ.get("HAFISCAL_JAX_MC_SEED_COUNT", "4"))
        _ad_seeds = tuple(s + 10 * _k for s in range(_n_seeds))
        if os.environ.get("HAFISCAL_JAX_MC_REPLAY_AD", "").lower() in ("1", "on", "true"):
            # Fix C (draw-structure plan): replay-fed AD — iterate HARK's own
            # deterministic map (captured exogenous panel, fixed across
            # iterations) with the compiled replay kernel. No kernel PRNG, so
            # seeds/stratified/pool knobs are inert here; whole-cell reseeds
            # flow through the agent seeds the capture inherits. v1 bypasses
            # the AD solution cache (measurement harnesses quarantine ad_*).
            from jax_mc_replay_ad import solve_ad_recession_jax_replay
            solve_ad_recession_jax_replay(
                eco, eco.base_AggCons, num_max_iterations=num_iter,
                convergence_cutoff=cutoff, shock_type=shock_type, verbose=True)
            eco.store_ADsolution(shock_type)
            _sync_mrkv_prev(eco)
            _replay_ad_done = True
        else:
            _replay_ad_done = False
        # Fix A (draw-structure plan, G1 discriminator): route the kernel through the
        # stratified-shuffle Mrkv-transition path (jax_mc_ad_shuffle) so its
        # transition draws match the production HARK scheme (stratified is canonical
        # since BUG-044). use_shuffle is already hashed into the AD cache key, so the
        # two schemes cannot cross-hit. Costs the vmap fast paths; opt-in.
        _strat = os.environ.get(
            "HAFISCAL_JAX_MC_STRATIFIED", "").lower() in ("1", "on", "true")
        if not _replay_ad_done:
            cached_solve_ad_recession(
                {"AggEco": eco}, eco.base_AggCons,
                num_max_iterations=num_iter, convergence_cutoff=cutoff,
                shock_type=shock_type, seeds=_ad_seeds, use_shuffle=_strat,
                verbose=True)
            eco.store_ADsolution(shock_type)
    else:
        # HARK MC AD path — all four shock types route through solve_ad_recession
        # (the three sibling methods are thin wrappers that just set shock_type).
        # cached_solve_ad_recession_hark is a transparent passthrough when
        # HAFISCAL_USE_SOLUTION_CACHE is unset.
        _scache_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "..")
        if _scache_path not in sys.path:
            sys.path.insert(0, _scache_path)
        from solution_cache import cached_solve_ad_recession_hark
        cached_solve_ad_recession_hark(
            {"AggEco": eco},
            num_max_iterations=num_iter,
            convergence_cutoff=cutoff,
            shock_type=shock_type, name=shock_type,
            verbose=True,
        )
    # Clear the warm-start flag so it cannot leak into any later solve on this eco
    # (solve_ad_recession defaults to the cold flat-reset when the flag is absent/False).
    if getattr(eco, '_ad_warm_start', False):
        eco._ad_warm_start = False
    eco.switch_shock_type(shock_type)
    eco.restore_ADsolution(name=shock_type)
    print(f"  [run_recession_AD] AD solve took {time() - t_ad:.1f}s",
          flush=True)
    # R6b publish (2026-08-03, best-effort): eco.CFunc now holds the CONVERGED
    # belief for this shock_type (restored just above, all engines). Publish
    # it as the AD-belief sidecar so later runs/batteries can warm-start
    # (consume is HAFISCAL_AD_BELIEF_SEED-gated + fingerprint-gated at load;
    # save_ad_belief skips if a sidecar already exists is NOT the semantics —
    # it overwrites, which is fine: same config ⟹ same converged belief).
    try:
        from solution_cache import ad_belief as _adb_pub
        _adb_pub.save_ad_belief(
            eco, shock_type, ctx.get("parametrization"),
            engine=("jax_mc_replay_ad" if use_jax else "hark_mc"),
            mc_method=("jax_mc_2d_vmap"
                       if (use_jax and shock_type in JAX_AD_SUPPORTED_SCENARIOS)
                       else "hark_mc"))
        from solution_cache import record_reuse_event as _rre_pub
        _rre_pub("ad_belief_seed", "published", "none",
                 shock_type=shock_type,
                 engine=("jax_mc_replay_ad" if use_jax else "hark_mc"))
    except Exception:
        pass

    # ---- post-AD policy handling (owner ruling 2026-07-29) ----------------
    # KEEP THE AD LOOP'S CONVERGED cFunc. An extra solve after convergence is a
    # SNIFF TEST of whether the rule really converged -- not a correction -- so
    # when it lands a tiny, meaningless distance from the prior solution the
    # right response is to DISCARD the test and keep the prior cFunc.
    #
    # Until this ruling the extra solve happened by ACCIDENT and only on some
    # paths: `restore_ADsolution` does not refresh `MrkvArray_prev`, so whether
    # the first post-AD `run_experiment` re-solved depended on what the AD loop
    # happened to leave behind (HARK's loop sets it via its own solve() calls;
    # the JAX loop does not). MEASURED at HS_Only recessionCheck_AD: HARK
    # duration loop 5.2 s / 0 solves vs JAX 39.5 s / 1 solve costing 34.1 s --
    # the same single wasted solve scaled to ~3200 s at Baseline and was the
    # entire "JAX makes HARK simulation 16x slower" effect.
    #
    # REQUIRED here, not redundant: this path installs a stored solution without
    # calling solve(), so `_parallel_agg_solve`'s own sync never runs for it.
    _sync_mrkv_prev(eco)

    _grid = np.linspace(0.5, 40.0, 400)
    _ones = np.ones_like(_grid)

    def _policy_snapshot():
        """Evaluate every agent's every Markov-state cFunc on a fixed grid.
        The comparable, engine-agnostic measure of 'the policy'."""
        out = []
        for _a in eco.agents:
            for _cf in _a.solution[0].cFunc:
                try:
                    out.append(np.asarray(_cf(_grid, _ones), dtype=float))
                except TypeError:
                    out.append(np.asarray(_cf(_grid), dtype=float))
        return out

    def _policy_move(before, after):
        return max(float(np.max(np.abs(b - a) / np.maximum(np.abs(a), 1e-12)))
                   for a, b in zip(before, after))

    # DIAGNOSTIC (not production): polish the policy to a stated accuracy so two
    # engines can be compared on equal terms. The AD loop's warm-started solves
    # (1-2 Bellman iterations each) leave the policy a different distance from its
    # fixed point depending on how the engine's rule-path evolved -- MEASURED at
    # Baseline: HARK 1.5e-06 vs JAX 9.5e-03 from one extra solve. Comparing walls
    # or outputs across engines without equalising this compares two different
    # convergence targets. Production keeps the owner's rule (discard the sniff,
    # keep the converged cFunc); this flag exists for A/B work only.
    _polish_tol = os.environ.get("HAFISCAL_AD_POLISH_TOL", "").strip()
    if _polish_tol:
        _tol_p = float(_polish_tol)
        _t_p = time()
        _moves = []
        for _k in range(int(os.environ.get("HAFISCAL_AD_POLISH_MAXIT", "12"))):
            _b = _policy_snapshot()
            eco.solve()
            _mv = _policy_move(_b, _policy_snapshot())
            _moves.append(_mv)
            if _mv < _tol_p:
                break
        _sync_mrkv_prev(eco)
        print(f"  [AD polish] {len(_moves)} extra solve(s) to reach {_tol_p:.0e}; "
              f"policy moves {[f'{m:.2e}' for m in _moves]} "
              f"({time() - _t_p:.1f}s)", flush=True)

    # Slow-accurate tier ONLY: run the sniff test, report the distance, then
    # throw the test solution away. Never wired into standard/fast.
    if os.environ.get("HAFISCAL_AD_SNIFF_TEST", "").lower() in ("1", "on", "true"):
        _before = _policy_snapshot()
        _saved = [_a.solution for _a in eco.agents]
        _t_sniff = time()
        eco.solve()
        _after = _policy_snapshot()
        _worst = max(
            float(np.max(np.abs(b - a) / np.maximum(np.abs(a), 1e-12)))
            for a, b in zip(_before, _after))
        for _a, _sol in zip(eco.agents, _saved):
            _a.solution = _sol          # DISCARD the test solution
        _sync_mrkv_prev(eco)            # the discarded solve still left prev stale
        _tol = float(os.environ.get("HAFISCAL_AD_SNIFF_TOL", "1e-2"))
        _verdict = "CONVERGED" if _worst <= _tol else "NOT CONVERGED"
        print(f"  [AD sniff test] one extra solve moved the policy by "
              f"{_worst:.3e} (tol {_tol:.0e}) -> {_verdict}; test solution "
              f"DISCARDED, prior cFunc kept ({time() - _t_sniff:.1f}s)",
              flush=True)
        if _worst > _tol:
            import warnings
            warnings.warn(
                f"[AD sniff test] post-convergence solve moved the policy by "
                f"{_worst:.3e} > {_tol:.0e}: the AD rule is NOT converged to "
                f"the accuracy this tier claims. Tighten "
                f"HAFISCAL_AD_CONVERGENCE_TOL or investigate the AD loop.",
                stacklevel=2)

    # Verification path: if HAFISCAL_USE_JAX_MC_REPLAY=1, run a JAX replay
    # against HARK's captured shock_history + sim_birth outputs and report
    # bit-precision agreement. Diagnostic only — does NOT change the output.
    if os.environ.get('HAFISCAL_USE_JAX_MC_REPLAY', '').lower() in ('1', 'on', 'true'):
        if shock_type == 'recession':
            try:
                from jax_mc_replay_production import verify_jax_replay_matches_hark
                _vr = verify_jax_replay_matches_hark(
                    parametrization=ctx.get('parametrization', 'HS_Only'),
                    shock_type='recession', verbose=True)
                print(f"  [jax-mc-replay] mean ratio: {_vr['mean_ratio']:.6f}, "
                      f"max |rel diff|: {_vr['max_rel_diff']:.6f}, "
                      f"passes (<1e-3): {_vr['passes']}", flush=True)
            except Exception as _e:
                print(f"  [jax-mc-replay] FAILED: {_e}", flush=True)
        else:
            print(f"  [jax-mc-replay] skipping for {shock_type} "
                  f"(this inline check is wired for 'recession' only; replay v2 "
                  f"supports all 4 policies via verify_welfare_replay.py)", flush=True)
    return _prob_weighted_rec(ctx, eco, changes,
                              duration_workers=duration_workers)


_DISPATCH = {
    "base":                  ("base",         None, None),
    "Check":                 ("norec",        "Check",        "Check_changes"),
    "UI":                    ("norec",        "UI",           "UI_changes"),
    "TaxCut":                ("norec",        "TaxCut",       "TaxCut_changes"),
    "recession":             ("recession",    "recession",    "recession_changes"),
    "recessionUI":           ("recession",    "recessionUI",  "recession_UI_changes"),
    "recessionCheck":        ("recession",    "recessionCheck", "recession_Check_changes"),
    "recessionTaxCut":       ("recession",    "recessionTaxCut", "recession_TaxCut_changes"),
    "recession_AD":          ("recession_AD", "recession",    "recession_changes"),
    "recessionUI_AD":        ("recession_AD", "recessionUI",  "recession_UI_changes"),
    "recessionCheck_AD":     ("recession_AD", "recessionCheck", "recession_Check_changes"),
    "recessionTaxCut_AD":    ("recession_AD", "recessionTaxCut", "recession_TaxCut_changes"),
}


def run_one_scenario(ctx, scenario, duration_workers=1, ad_tolerance=None):
    kind, shock_type, changes_key = _DISPATCH[scenario]
    if kind == "base":
        return run_base(ctx)
    changes = ctx[changes_key]
    if kind == "norec":
        return run_norec(ctx, shock_type, changes)
    if kind == "recession":
        return run_recession(ctx, shock_type, changes,
                             duration_workers=duration_workers)
    if kind == "recession_AD":
        return run_recession_AD(ctx, shock_type, changes,
                                duration_workers=duration_workers,
                                ad_tolerance=ad_tolerance)
    raise ValueError(kind)


def main():
    """CLI entry point: run ONE welfare-6 scenario in this process and pickle it.

    Parses --scenario / --parametrization / --seed-offset / parallelism args
    (see the argparse help and the module docstring), builds and solves the
    economy via build_and_solve, always runs the base scenario first (the
    store_baseline prerequisite for AD scenarios), then runs the requested
    scenario and writes <out_dir>/<scenario>.pkl with the agent-level
    consumption/income panels consumed by the welfare-6 formula (payload
    includes the BUG-051 regime stamp).

    Side effects: sets the module global _SOLVE_WORKERS, creates out_dir,
    prints timing/parallelism diagnostics.
    """
    p = argparse.ArgumentParser()
    p.add_argument("--scenario", required=True, choices=SCENARIOS)
    p.add_argument("--parametrization", default="Reduced_Run",
                   help="Parametrization name passed to "
                        "Parameters.return_parameters(). Includes "
                        "Baseline, Reduced_Run, HS_Only, College_Beta_Het, Smoke_Test, and "
                        "the sensitivity names: CRRA1, CRRA3, ADElas, "
                        "Rfree_1005, Rfree_1015, Rspell_4, LowerUBnoB, "
                        "Splurge0 (and their *_PVSame variants). "
                        "Parameters.py rejects unknown names.")
    p.add_argument("--baseline", action="store_true",
                   help="Alias for --parametrization Baseline.")
    p.add_argument("--duration-workers", type=int, default=None,
                   help="Number of forked worker processes for the "
                        "recession-duration loop (only applies to "
                        "recession and recession_AD scenarios). Default: "
                        "auto (budgeted from cpu_count; see "
                        "_auto_standalone_parallel_plan).")
    p.add_argument("--solve-workers", type=int, default=None,
                   help="Number of forked worker processes for the "
                        "per-agent-type solve inside "
                        "AggregateDemandEconomy.solve(). Applies to every "
                        "solve() call (initial, per-scenario, and every "
                        "AD-convergence iteration). Default: auto "
                        "(budgeted from cpu_count).")
    p.add_argument("--ad-tolerance", type=float, default=None,
                   help="Override convergence_tol_solvingAD for the "
                        "AD scenarios in this run. Default: use the value "
                        "from Parameters.py (1E-3; 1E-2 for the reduced "
                        "parametrizations Reduced_Run/Smoke_Test/HS_Only). "
                        "Loosening typically cuts 1-2 iterations.")
    p.add_argument("--agent-count-total", type=int, default=None,
                   help="Override AgentCountTotal from Parameters.py. "
                        "Baseline defaults to 10000; halving to 5000 "
                        "roughly halves per-scenario work. CRN pairing "
                        "in welfare6 tends to be robust to moderate N "
                        "reductions but verify before adopting.")
    p.add_argument("--seed-offset", type=int, default=0,
                   help="Integer offset added to per-agent-type seeds "
                        "(stride 10000) and to IncShkDstn seed (stride 1). "
                        "0 is the canonical run; non-zero values produce "
                        "independent multi-seed batches. CRN within a "
                        "single seed_offset is preserved across all 12 "
                        "scenarios; across offsets, panels are independent.")
    p.add_argument("--out-dir", default=None,
                   help="Directory to write pickle (default: "
                        "welfare6_scenario_results/ inside FromPandemicCode/).")
    args = p.parse_args(_ORIG_ARGV[1:])

    parametrization = "Baseline" if args.baseline else args.parametrization
    out_dir = args.out_dir or os.path.join(HERE, "welfare6_scenario_results")
    os.makedirs(out_dir, exist_ok=True)

    # Companion heuristic for standalone runs (no outer parallel driver).
    # When --solve-workers / --duration-workers are not given, budget
    # inner parallelism from cpu_count(). For a recession scenario:
    # prefer duration-workers (20 durations) first, then solve-workers
    # (21 types) from residual. For non-recession: all budget to
    # solve-workers.
    _is_rec = args.scenario.startswith("recession")
    # Allocation-aware count: under a SLURM cgroup / taskset, os.cpu_count()
    # reports the whole node while the cpuset is the real grant.
    try:
        _ha_mp = os.path.abspath(os.path.join(HERE, ".."))
        if _ha_mp not in sys.path:
            sys.path.insert(0, _ha_mp)
        from machine_profile import effective_cpu_count as _eff_cpu
        _cpu = _eff_cpu()
    except Exception:
        _cpu = os.cpu_count() or 1
    _N_AGENT_TYPES, _N_DURATIONS = 21, 20
    if args.solve_workers is None and args.duration_workers is None:
        if _is_rec:
            # Post-BUG-064 the duration pool SCALES (6.07x at dw=8, re-measured
            # 2026-07-30; see run_welfare6_parallel._auto_parallel_plan and its
            # measurement note). The dw=2 cap this block used to carry was
            # calibrated 2026-07-28 WITH the bug live — the dw>=4 degradation
            # (dw=11 308s; Baseline dw=20 7582s) was each forked child
            # re-solving the economy, not fork COW; test_duration_no_resolve
            # guards the fix. Mirror the battery driver's plan: the solve
            # phase and the duration phase are sequential, so neither splits
            # its core budget with the other.
            _auto_dw = min(8, _N_DURATIONS, _cpu)
            _auto_sw = min(_N_AGENT_TYPES, _cpu)
        else:
            _auto_dw = 1
            _auto_sw = min(_N_AGENT_TYPES, _cpu)
        _solve_w    = _auto_sw
        _duration_w = _auto_dw
        print(f"[auto-parallel] cpu={_cpu} scenario={args.scenario} "
              f"→ solve-workers={_solve_w}  duration-workers={_duration_w}",
              flush=True)
    else:
        _solve_w    = 1 if args.solve_workers    is None else int(args.solve_workers)
        _duration_w = 1 if args.duration_workers is None else int(args.duration_workers)

    # Install the resolved --solve-workers value before build_and_solve,
    # so every AggregateDemandEconomy.solve() call in this process uses
    # the requested parallelism level.
    global _SOLVE_WORKERS
    _SOLVE_WORKERS = max(1, int(_solve_w))

    t0 = time()
    ctx = build_and_solve(parametrization,
                          agent_count_total=args.agent_count_total,
                          seed_offset=args.seed_offset)
    ctx["_seed_offset"] = int(args.seed_offset)
    # If we're running base, store_baseline is called inside run_base.
    # If we're running ANY scenario, the AggEco we built needs a base call
    # before AD scenarios can call store_ADsolution (which depends on
    # stored_solutions being initialized by store_baseline). So always
    # establish the baseline first, then run the requested scenario.
    # R3 base-share (2026-08-02): the only cross-child consumers of the
    # base run are store_baseline's AggCons vector (the AD reference path
    # + the recorded Cratio_hist); the panels serve only the base child's
    # own pkl. So non-base children first try the shared vector (published
    # by any prior base run under the SIM key) and only re-simulate base
    # on a MISS. store_baseline itself snapshots the CURRENT solve state,
    # which run_base does not alter (build_and_solve solved under the base
    # config), and every run_experiment re-seeds its RNG streams — so the
    # skip is exact for all downstream panels (byte-gated at adoption).
    # KEY STATE POINT: the SIM key hashes live agent params, which the base
    # run itself mutates (update_mrkv_array rebuilds objects) — so resolve
    # the key ONCE here, pre-run, and use it for BOTH load and save.
    base_mc = None
    try:
        from solution_cache import (base_aggcons_paths,
                                    load_base_aggcons_cache,
                                    save_base_aggcons_cache)
        _bs_paths = base_aggcons_paths(ctx["AggEco"],
                                       base_dict=ctx["base_dict"],
                                       seed_offset=int(args.seed_offset))
    except Exception:
        _bs_paths = None
    if args.scenario != "base":
        _shared_aggcons = (
            load_base_aggcons_cache(ctx["AggEco"], paths=_bs_paths)
            if _bs_paths is not None else None)
        if _shared_aggcons is not None:
            _ensure_base_solved(ctx["AggEco"])
            ctx["AggEco"].store_baseline(_shared_aggcons)
        else:
            run_base(ctx)
            if _bs_paths is not None:
                save_base_aggcons_cache(ctx["AggEco"],
                                        ctx["AggEco"].base_AggCons,
                                        paths=_bs_paths)
    else:
        base_mc = run_base(ctx)
        if _bs_paths is not None:
            save_base_aggcons_cache(ctx["AggEco"],
                                    ctx["AggEco"].base_AggCons,
                                    paths=_bs_paths)
    t_build = time() - t0

    if args.scenario == "base":
        r = base_mc
    else:
        t0b = time()
        r = run_one_scenario(ctx, args.scenario,
                             duration_workers=_duration_w,
                             ad_tolerance=args.ad_tolerance)
        t_scenario = time() - t0b
        tol_tag = (f"ad_tol={args.ad_tolerance}"
                   if args.ad_tolerance is not None else "ad_tol=default")
        print(f"[{args.scenario}] ran in {t_scenario:.0f}s "
              f"(setup {t_build:.0f}s, duration_workers="
              f"{_duration_w}, solve_workers="
              f"{_SOLVE_WORKERS}, {tol_tag})")

    out_path = os.path.join(out_dir, f"{args.scenario}.pkl")
    # BUG-046: also persist per-duration cLvl_all_splurge for correct
    # welfare aggregation (avoid Jensen bias from u(dur-averaged c)).
    _per_dur_cLvl = r.get("per_dur_cLvl_all_splurge", None)
    _rec_probs = r.get("rec_probs", None)
    payload = {
        "scenario":       args.scenario,
        "parametrization": parametrization,
        "cLvl_all_splurge": np.array(r["cLvl_all_splurge"]),
        "AggCons":          np.array(r["AggCons"]),
        "AggIncome":        np.array(r["AggIncome"]),
        # Bootstrap-source panel. For non-recession scenarios, these
        # are identical to the primary fields. For recession scenarios,
        # cLvl_all_splurge is probability-weighted across 20 duration
        # realizations, but *_bs is a single-duration snapshot (dur=0,
        # the modal duration) used by the control-variate bootstrap.
        # Under CRN with perm_shocks_during_unemployment=True (Baseline
        # parametrization), pLvl_all_bs is invariant across scenarios;
        # it is persisted per-scenario for self-containment.
        "cLvl_all_splurge_bs": np.asarray(r["cLvl_all_splurge_bs"]),
        "pLvl_all_bs":         np.asarray(r["pLvl_all_bs"]),
        "Mrkv_hist_bs":        np.asarray(r["Mrkv_hist_bs"]).astype(np.int32),
        # JAX-MC validation: aNrm_all_bs allows the JAX kernel to use
        # HARK's exact post-warmup asset state as its initial condition.
        # Backward-compatible: existing consumers ignore the key.
        **({"aNrm_all_bs": np.asarray(r["aNrm_all_bs"])}
           if "aNrm_all_bs" in r else {}),
        **({"TranShk_all_bs": np.asarray(r["TranShk_all_bs"])}
           if "TranShk_all_bs" in r else {}),
        **({"PermShk_all_bs": np.asarray(r["PermShk_all_bs"])}
           if "PermShk_all_bs" in r else {}),
        **({"who_dies_all_bs": np.asarray(r["who_dies_all_bs"])}
           if "who_dies_all_bs" in r else {}),
        "act_T":            ctx["act_T"],
        "Rfree":            ctx["Rfree"],
        "CRRA":             ctx["CRRA"],
        "runtime_s":        time() - t0,
        # Matched-pair regime stamp (BUG-051): lets the TM-vs-MC comparison
        # refuse to compare a pickle from a different PermGroFac / UI-encoding /
        # interpretation regime. Mirrors welfare6_hybrid_table.capture_welfare6_regime.
        "regime": {
            "permgrofac_fix": os.environ.get("HAFISCAL_PERMGROFAC_FIX", "1") != "0",
            "ui_state_encoding": os.environ.get("HAFISCAL_UI_STATE_ENCODING", "bug_fix"),
            "interpretation": (os.environ.get("HAFISCAL_INTERPRETATION") or "CDC").upper(),
        },
    }
    if _per_dur_cLvl is not None:
        payload["per_dur_cLvl_all_splurge"] = np.asarray(_per_dur_cLvl)
        payload["rec_probs"] = np.asarray(_rec_probs)
    with open(out_path, "wb") as f:
        pickle.dump(payload, f, protocol=pickle.HIGHEST_PROTOCOL)
    print(f"[{args.scenario}] saved: {out_path} "
          f"({time() - t0:.0f}s wall)")

    # Provenance: standalone runs get a sidecar next to the pickle. Suppressed
    # when spawned by run_welfare6_parallel.py (it emits one aggregate sidecar).
    if os.environ.get("HAFISCAL_PROV_CHILD") != "1":
        _emit_provenance_sidecar(
            [out_dir], label=f"welfare6_scenario-{args.scenario}",
            output_roots=[out_path],
        )
    else:
        # Battery child (sidecar-suppressed): dump the reuse ledger as a
        # dotfile fragment; the driver ingests it into its aggregate sidecar
        # (schema v2, plan 20260803-0900h P1).
        try:
            _ha_frag = os.path.abspath(os.path.join(HERE, ".."))
            if _ha_frag not in sys.path:
                sys.path.insert(0, _ha_frag)
            import provenance as _prov_frag
            _prov_frag.dump_reuse_fragment(
                out_dir, label=f"welfare6_scenario-{args.scenario}")
        except Exception:
            pass


if __name__ == "__main__":
    # Canonical welfare engine (owner-adopted 2026-08-02): resolve + apply the
    # hybrid default bundle to os.environ BEFORE any routing reads it.
    # Entry-point only — importing this module never mutates the environment.
    # HAFISCAL_WELFARE_ENGINE=hark (or the as-corrected/QE-fidelity worlds)
    # restores the pre-arc path. See plans/20260802-0300h and
    # Code/HA-Models/welfare_engine.py.
    try:
        from welfare_engine import apply_welfare_engine_defaults
        apply_welfare_engine_defaults()
    except Exception as _we_e:  # pragma: no cover - never abort a run
        print(f"[welfare6] welfare_engine unavailable ({_we_e}); "
              "running with the raw environment", flush=True)
    main()
