name: hafiscal
channels:
  - conda-forge
dependencies:
  - python=3.11.7
  - econ-ark=0.14.1
  - numpy=1.26.4
  - matplotlib=3.8.0
  - scipy=1.11.4
  - pandas=2.1.4
  - numba=0.59.0
  - voila
  - pip
  - pip:
    - sequence-jacobian